name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches:
      - main
      - release/**/*

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install functions dependencies
        run: npm ci
        working-directory: ./functions

      - name: Run lint
        run: npm run lint

      - name: Run lint (functions)
        run: npm run lint
        working-directory: ./functions

      - name: Run tests
        run: npm run test

      - name: Build app
        run: npm run build

      - name: Install Vercel CLI
        if: github.ref == 'refs/heads/main'
        run: npm install -g vercel

      - name: Deploy to Vercel
        if: github.ref == 'refs/heads/main'
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: vercel --prod --token $VERCEL_TOKEN